# Generated by Django 4.0.5 on 2022-11-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blackboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackboard',
            name='is_validated',
        ),
    ]
