# Generated by Django 4.0.5 on 2022-10-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackboard', '0002_recipe_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blackboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('recipes', models.ManyToManyField(to='Blackboard.recipe')),
            ],
        ),
    ]
