# Generated by Django 4.0.5 on 2022-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackboard', '0002_remove_blackboard_is_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
