# Generated by Django 4.0.5 on 2022-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackboard', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackboard',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
