# Generated by Django 4.0.5 on 2022-10-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blackboard', '0003_blackboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackboard',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pasta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Blackboard.pasta'),
        ),
    ]
