# Generated by Django 4.0.5 on 2022-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackboard', '0004_blackboard_is_validated_alter_recipe_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackboard',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='keyingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
