# Generated by Django 4.0.5 on 2022-10-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blackboard', '0005_alter_blackboard_date_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Blackboard.pasta'),
        ),
    ]
